### ISSUE TITLE
Pre-Alpha V4 Feature List #1

### ISSUE THREAD

**Issue by sebulba69** [sebulba69/AscendedZ#28]
Goal: Tiers 41 -> 100 (stops at 101)
✅ = complete

Refactors: ✅
* Backgrounds should read from background folders instead of being hardcoded: Overworld, Battle ✅
* Music should read from music folders instead of being hardcoded: Overworld, Battle, Boss ✅
* Make the Boss UI consistent with the other party member UIs ✅
* Replace PackedScene instantiations with their respective objects
* Fix calculations for enemy HP so it does not have to divide large numbers into smaller ones
* OPTIONAL: Add BigInteger support for the main game

Balancing changes:
* Quests
a. Reduce VC gain from Quests. ~~VC gain should be based on an enemy-by-enemy basis for tier completions.~~ ✅
b. Simplify Battle Quests to only require a turn count & certain party members ✅
c. Simplify Delivery Quests to just require the party member ✅
* ~~Increase VC gain from tier completions~~ <-- Reducing due to the alt ways of getting Vorpex being added ✅
* Reduce HP gain for enemies during normal progression (includes the bosses that force upgrades) ✅
* Remove the HP adjustments for mid-late game bosses ✅
* Add Vorpex Values from Materials as an average for upgrading during Fusion ✅
* Reduce stat increases from Upgrading (should move to Armor instead) ✅
* Reduce the Shop Price scaling for buying more party members ✅

UI Updates/Fixes:
* Have HP displays be HP/MaxHP ✅
* Fix a bug with the boss HP bar where it'll add an extra "bar" if current value = max value ✅
* Clarify in Delivery Quests that a party member is lost to deliver one for the quest ✅
* Rework Quest UI to have a list of possible quests and the Quest Complete Button in the description of each quest ✅
* Change "VS" in the Upgrade Screen to "VC" ✅
* Rework the Battle UI ✅
a. Move Turn Icons back to where they were before ✅
b. Make the Action Menu wider, but don't let it affect the Party Member display size ✅

New Enemies:
* More ~~Resistance swappers~~ Copy Cats but with less favorable resistances like Nulls or Drains ✅
* More WEX enemies but with less favorable resistances like above ✅
* More AGRO enemies but with less favorable resistances like above ✅
* Introduce Hell AI into the enemy pool (T41 -> 50)
* Introduce generic Hell Boss AI (50 -> 100) - Goal: Randomly generate bosses that are programmed to use whatever skills they're given in optimal ways. This should only be done if a specific boss does not exist in the Enemy Factory

Dungeon Crawling - The Buceldome: Issue #29 ✅
* Procedurally generated dungeon with a different combat system from the main gameplay ✅
* ~~Dungeons use your MainPlayer instead of your typical party~~
* A separate currency, Dellencoin, is used for shops that show up as you traverse the dungeon (reference to Ascended 0)
* ~~Shop keepers will alternate like in Ascended 0~~
* The goal is to find the stairs and ascend to the top floor ✅
* ~~Every 10 floors has a unique boss (different from the main game)~~ Moving this to the Idle Game (will add later)
* ~~MainPlayer gets skills through armor (like in Ascended 0) that they find throughout the dungeon (Head, Torso, Arms, Waist, Legs, Charms)~~
* ~~Shop Vendors also sell armor that's missing~~
* ~~When escaping the Dungeon, Armor that was obtained gets turned into Armor that your Party can use in the Endless Dungeon. The conversion rate is based on the elements present on the Armor in-dungeon (Fire Skills = Fire Boost).~~
* ~~The Armor also gets converted into stats your Main Player has when embarking into the dungeon again~~
* ~~Your default skill is called "Attack" and it's Physical based~~
* ~~All skills require a cost (HP/MP)~~
* ~~Dungeons will have other events that can impact the main game (not decided on yet)~~ See the Dungeon Crawling ticket for info on the events

~~New Upgrade Features: [EDIT: To be moved to its own ticket.]~~
* ~~Armor System: A revamped version of Ascended 0's Armor
a. Head, Torso, Arms, Waist, Legs
b. Starting implementation: Each armor piece has a % stat boost to an Element (does not include healing) or a defense boost (increased HP - also a percentage)
c. Armor is obtainable through the Buceldome (see "Dungeon Crawling" section)
d. Collected armor pieces can be fused together to boost stats (Stats1 + Stats2 / 1.5)~~

~~* Minion Hut: A revamped version of the Minion Hut from Ascended 0
a. Minions are additional party members you can bring into the Buceldome (see "Dungeon Crawling")
b. You can upgrade them with Minion Shards obtained from the Buceldome
c. They provide extra skills for you to use in battle: Red = Elemental Skills, Green = Support Skills, Blue = Buffs/Debuffs
d. You can only equip 1 minion of each type per Dungeon run
e. MAX Upgraded Minions (lvl 999) can be smelted for VC (1000) or prestiged for increased scaling while leveling up (also more VC gain if smelted)
f. Minions are also used for the Bounty Bosses~~

* Bounty Bosses
[TO BE DETERMINED AND PLACED INTO ITS OWN TICKET]

~~* Element Stat + Heal Stat Screen: A revamped version of Ascended 0's armor upgrading
a. Every time a party member is in your party when a tier is completed, they gain XP at the end for the number of enemies on that tier (does not include bosses) equal to the tier range/10 (tiers 1 -> 10 give 1 XP, tiers 11 -> 20 give 2 XP, etc.)
b. You can increase each stat by 1 for each XP you have. The cost increases by 1 for a stat every level~~

**Comment by Crystalwarrior** [comment]
im feeling nostalgic for some reason

**Comment by sebulba69** [comment]
Pre-Alpha v4 is out
